### ISSUE TITLE
What is the right way to import a package from lerna-starter?

### ISSUE THREAD

**Issue by adamchenwei** [garmeeh/lerna-starter#7]

**Comment by garmeeh** [comment]
Apologies for the *very* reply on this. I missed the notification coming threw on this over Christmas. 

Have you figured this out? If not can you give me a bit more context on the problem you are having? 

Are you looking to know how to import the package within the monorepo itself?

**Comment by adamchenwei** [comment]
so basically import a specific component from learna starter 's example component to another project I work on.

**Comment by garmeeh** [comment]
If you are in a position to, the best way would be to publish the packages/components to npm and then install them to your other project. 

Otherwise, the answer [here](https://github.com/lerna/lerna/issues/536#issuecomment-275984463) on the lerna repo goes into a bit of detail on the alternative options.
